# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       nemo-configs-x86

# >> macros
# << macros

Summary:    Some configs for x86-generic adaptation in Nemo Mobile
Version:    0.1
Release:    1
Group:      Configs
License:    GPLv2
BuildArch:  noarch
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-configs-x86.yaml

%description
%{summary}.


%package vm
Summary:    Configs for x86 vm adaptation
Group:      Configs
Provides:   nemo-mobile-configs-x86-vm > 2
Obsoletes:  nemo-mobile-configs-x86-vm <= 2

%description vm
%{summary}.


%package generic
Summary:    Configs for generic x86 adaptation
Group:      Configs
Provides:   nemo-mobile-configs-x86-generic > 2
Obsoletes:  nemo-mobile-configs-x86-generic <= 2

%description generic
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%make_install
# << install pre

# >> install post
# << install post


%files vm
%defattr(-,root,root,-)
%{_sharedstatedir}/environment/nemo/61-x86-vm.conf
%{_sharedstatedir}/environment/compositor/61-x86-vm-ui.conf
# >> files vm
# << files vm

%files generic
%defattr(-,root,root,-)
%{_sharedstatedir}/environment/nemo/61-x86-generic.conf
# >> files generic
# << files generic
